spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-calm-brook-an71yidi-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_NB0Vtce1hjxw&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NB0Vtce1hjxw
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
